name: audio_player_background
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.14.0
  audio_session: ^0.0.4
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  just_audio: ^0.4.1
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.11
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - audios/
